on: [push]

env:
  PYTHON_VERSION: '3.7'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 flake8-bugbear flake8_simplify
        pip install pytest pyyaml requests jinja2 deepmerge
        wget -O - https://raw.githubusercontent.com/jirutka/esh/master/esh >/usr/local/bin/esh
        chmod +x /usr/local/bin/esh
    - name: Flake8
      run: |
        flake8 -v
    - name: Pytest
      run: |
        python -m pytest -v

  build:
    needs: [lint]
    if: needs.lint.result == 'success' && contains(github.ref, '/tags/') && startsWith(github.ref_name, 'v')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry poetry-dynamic-versioning-plugin
    - name: Build
      run: |
        poetry build
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_URL: ${{ github.server_url	}}
        GITHUB_REPO: ${{ github.repository }}
        GITHUB_TAG: ${{ github.ref_name }}      
      run: |
        RELEASE_MESSAGE=$(hub release -L 1)
        RELEASE_MESSAGE="**Full Changelog**: ${GITHUB_URL}/${GITHUB_REPO}/compare/${RELEASE_MESSAGE}...${GITHUB_TAG}"
        echo $GITHUB_TAG >.message
        echo "" >>.message
        echo "${RELEASE_MESSAGE}" >>.message
        hub release create -a $(find dist -name '*.tar.gz') -a $(find dist -name '*.whl') -F .message $GITHUB_TAG
    - name: Publish
      env:
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      run: |
        poetry publish -u "__token__" -p "${PYPI_TOKEN}"
        
        

